# Generated by Django 5.0.7 on 2025-02-11 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="register_model",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=70)),
                ("email", models.EmailField(max_length=254)),
                ("passw", models.CharField(max_length=40)),
                ("cpassw", models.CharField(max_length=40)),
                ("phone_no", models.CharField(blank=True, max_length=100, null=True)),
                ("Address", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "date_of_birth",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="slot",
            name="booked_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="myapp.register_model",
            ),
        ),
        migrations.DeleteModel(
            name="CustomUser",
        ),
    ]
