# Generated by Django 5.0.7 on 2025-02-11 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_register_model_alter_slot_booked_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="register_model",
            name="date_of_birth",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
