# Generated by Django 5.0.7 on 2025-02-11 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_alter_register_model_date_of_birth"),
    ]

    operations = [
        migrations.AlterField(
            model_name="register_model",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
    ]
