# Generated by Django 5.0.7 on 2025-03-09 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_alter_register_model_date_of_birth"),
    ]

    operations = [
        migrations.CreateModel(
            name="adminregister",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=70)),
                ("email", models.EmailField(max_length=254)),
                ("passw", models.CharField(max_length=40)),
                ("cpassw", models.CharField(max_length=40)),
                ("phone_no", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name="slot",
            name="end_time",
            field=models.DateTimeField(editable=False),
        ),
    ]
