# Generated by Django 5.0.7 on 2025-03-18 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0006_teacher_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="status",
            field=models.CharField(
                choices=[("Free", "Free"), ("Busy", "Busy")],
                default="Free",
                max_length=10,
            ),
        ),
    ]
